name: Trigger Analyzer

on:
  pull_request:
    branches:
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Analyzer Repo
        run: |
          curl -X POST https://api.github.com/repos/tuhinchowdhury/agentic_AI_new/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -d '{
            "event_type": "run-analyzer",
            "client_payload": {
              "repo": "agentic_AI_new_bff",
              "pr_number": '${{ github.event.pull_request.number }}'
            }
          }'