name: Trigger Analyzer

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Event
        run: |
          echo "EVENT NAME: ${{ github.event_name }}"

      - name: Trigger Analyzer Repo
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}

          # fallback for push event
          if [ -z "$PR_NUMBER" ]; then
            PR_NUMBER=0
          fi

          curl -X POST https://api.github.com/repos/tuhinchowdhury/agentic_AI_new/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -d "{\"event_type\":\"run-analyzer\",\"client_payload\":{\"pr_number\":\"$PR_NUMBER\"}}"